language: cpp
compiler: gcc
os:
    - linux
sudo: required

branches:
    only:
        - master

addons:
    sonarcloud:
        organization: "neueda-blu-corner"

before_install:
    - sudo apt-get update
    - sudo apt-get install -y vera++ cppcheck valgrind gcovr

before_script:
    - mkdir build
    - cd build
    - export LD_LIBRARY_PATH=`pwd`/install/lib

script:
    - cmake -DTESTS=ON ../
    - make VERBOSE=1 install 2>&1 | tee compiler.log
    - valgrind --xml=yes --xml-file=valgrind_report.xml -- ./install/bin/unittest --gtest_output=xml:./test.xml
    - cppcheck -f --enable=all --suppress=missingIncludeSystem --xml ../src/ ../test/ 2> ./cppcheck_report.xml
    - vera++ -c vera.xml `find ../src/ -regextype posix-egrep -regex ".*\\.(cc|cpp|h|hpp)"`
    - gcovr -r ./ -x > coverage_report.xml
    - sonar-scanner -Dsonar.cxx.cppcheck.reportPath=cppcheck_report.xml -Dsonar.cxx.vera.reportPath=vera.xml -Dsonar.cxx.valgrind.reportPath=build/valgrind_report.xml -Dsonar.cxx.coverage.reportPath=coverage_report.xml -Dsonar.cxx.compiler.parser=GCC -Dsonar.cxx.compiler.reportPath=compiler.log -Dsonar.cxx.compiler.charset=UTF-8 -Dsonar.sources=../src/
